"""init

Revision ID: 01ea466496e3
Revises: 
Create Date: 2026-07-17 15:40:38.828420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ea466496e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=20), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('current_status', sa.String(length=200), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_receipt_number'), ['receipt_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_receipt_number'))

    op.drop_table('cases')
    # ### end Alembic commands ###
