"""add usps_tracking and mailed_date

Revision ID: a3f683745a13
Revises: 01ea466496e3
Create Date: 2026-07-17 19:33:50.268926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f683745a13'
down_revision = '01ea466496e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usps_tracking', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('mailed_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('mailed_date')
        batch_op.drop_column('usps_tracking')

    # ### end Alembic commands ###
